name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World"
      - name: "Segunda ação"
        run: |
          echo "Voce laala"
          echo "teste"
      - name: "script python do Abner"
        run: |
          variavel = "NO WAY, DUDE!!!"
          print(variavel)
        shell: python
  segundo-job:
      name: "Não sei o que é - instalação do ambiente node.js"
      runs-on: ubuntu-latest
      steps:
        - name: "versão node.js" 
          run: node -v
        - name: "DEFININDO NOVA VERSÃO DO NODE"
        - uses: actions/setup-node@v6
          with: # Aqui entram os parâmetros
            node-version: '20.13.1'
        - name: "Nova versão node.js" 
          run: node -v
          
        
